### ISSUE TITLE
worldserver segfault

### ISSUE THREAD

**Issue by braddevans** [josefalcon/trinitycore-docker#8]
```
 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
```
http://TrinityCore.org                    \/__/
Using configuration file /opt/trinitycore/conf/worldserver.conf.
Using SSL version: OpenSSL 1.0.2s  28 May 2019 (library: OpenSSL 1.0.2s  28 May 2019)
using Boost version: 1.62.0
Updating Auth database...
>> Auth database is up-to-date! Containing 3 new and 46 archived updates.
Updating Character database...
>> Character database is up-to-date! Containing 1 new and 33 archived updates.
Updating World database...
/etc/entrypoint.sh: line 165:    13 Segmentation fault      (core dumped) /usr/local/bin/worldserver -c $CONF_DIR/worldserver.conf

**Comment by kirbysayshi** [comment]
This repo is fairly unmaintained and we didn't really know what we were doing regarding docker when we started.

Also, without seeing the command you ran to get that output, it's very hard to debug.
